import { useState } from 'react';
import axios from 'axios';

const demo = { admin: { username: 'admin', email: 'admin@dayflow.local', password: 'admin123' }, employee: { username: 'employee', email: 'employee@dayflow.local', password: 'employee123' } };

export default function AuthScreen({ onLogin }) {
  const [mode, setMode] = useState('login');
  const [role, setRole] = useState('admin');
  const [form, setForm] = useState({ ...demo.admin, full_name: '', employee_id: '' });
  const [verification, setVerification] = useState(null);
  const [error, setError] = useState('');
  const chooseRole = (nextRole) => { setRole(nextRole); setForm({ ...demo[nextRole], full_name: '', employee_id: '' }); setError(''); };
  const setField = (field, value) => setForm({ ...form, [field]: value });
  const login = async (event) => { event.preventDefault(); setError(''); try { const { data } = await axios.post('/api/auth/login', { email: form.email, username: form.username, password: form.password, login_as: role }); localStorage.setItem('dayflow_user', JSON.stringify(data.user)); localStorage.setItem('dayflow_token', data.access_token); axios.defaults.headers.common.Authorization = `Bearer ${data.access_token}`; onLogin(data.user); } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to sign in'); } };
  const register = async (event) => { event.preventDefault(); setError(''); try { const { data } = await axios.post('/api/auth/register', { employee_id: form.employee_id || null, username: form.username, email: form.email, password: form.password, full_name: form.full_name, role }); setVerification({ email: form.email, token: data.verification_token }); } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to register'); } };
  const verify = async () => { try { await axios.post(`/api/auth/verify-email?email=${encodeURIComponent(verification.email)}&token=${encodeURIComponent(verification.token)}`); setMode('login'); setError('Email verified. Sign in to continue.'); } catch (requestError) { setError(requestError.response?.data?.detail || 'Verification failed'); } };
  return <main className="login-page"><section className="login-art"><div className="brand-mark">D</div><p className="eyebrow">DAYFLOW / PEOPLE OPERATIONS</p><h1>Make work<br /><em>flow better.</em></h1><p className="login-copy">A calm command center for your people, their time, and the work that moves your business forward.</p><div className="signal-card"><span className="pulse-dot" /> All systems operational <strong>Live</strong></div></section><section className="login-panel"><div className="login-inner"><p className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'JOIN DAYFLOW'}</p><h2>{mode === 'login' ? 'Good morning.' : 'Create your account.'}</h2><p className="muted">{mode === 'login' ? 'Choose your workspace and sign in.' : 'Your email must be verified before sign in.'}</p>{verification ? <div className="verification-box"><strong>Verify your email</strong><p className="muted">Your verification token is ready for this local demo.</p><button className="primary-button" onClick={verify}>Verify email <span>-&gt;</span></button></div> : <><div className="role-switch"><button type="button" className={role === 'employee' ? 'selected' : ''} onClick={() => chooseRole('employee')}>Employee</button><button type="button" className={role === 'admin' ? 'selected' : ''} onClick={() => chooseRole('admin')}>Admin / HR</button></div><form onSubmit={mode === 'login' ? login : register} className="login-form">{mode === 'register' && <><label>Employee ID<input value={form.employee_id} onChange={(e) => setField('employee_id', e.target.value)} placeholder="Employee ID" /></label><label>Full name<input required value={form.full_name} onChange={(e) => setField('full_name', e.target.value)} placeholder="Full name" /></label></>}<label>Email<input required type="email" value={form.email} onChange={(e) => setField('email', e.target.value)} placeholder="you@company.com" /></label><label>Username<input required value={form.username} onChange={(e) => setField('username', e.target.value)} /></label><label>Password<input required type="password" value={form.password} onChange={(e) => setField('password', e.target.value)} /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button">{mode === 'login' ? `Enter ${role === 'admin' ? 'HR' : 'employee'} workspace` : 'Create account'} <span>-&gt;</span></button></form><button className="auth-toggle" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setVerification(null); setError(''); }}>{mode === 'login' ? 'New here? Create an account' : 'Already registered? Sign in'}</button><p className="login-hint">Demo: {demo[role].email} / {demo[role].password}</p></>}</div></section></main>;
}
